#!/usr/bin/env python
"""PygLatin version 2 Copyright 2013 by Brandon Shockley using repl.it Python Editor. Have Fun Thanks! Please report bugs or Suggestions to @bcshockl or brandon.shockley@asu.edu"""

print "Welcome to PygLatin! A English to Piglatin Translator built from scratch using the Python Coding Language."
print""

def main(): 
        ay = "ay"
        og = raw_input("Please Enter The Word You Would Like To Translate And Press Return!  ")
        new = og.lower()
        if new.isalpha() and len(new) > 0:
            pass
        while new.isdigit() or len(new) < 0:
            print""
            new = raw_input("Please Try Again! Enter The Word You Would Like To Translate And Press Return!  ")
            new = new.lower()
        if new.isalpha() and len(new) > 0:
          pass
        if new[0] in ["a","e","i","o","u"]:
            print ""
            new = new[0].upper() + new[1:] + ay
            print "Your Word In PigLatin is " + new
            print ""
        elif new[0] not in ["a","e","i","o","u"]:
           letter = new[0]
           new = new[1].upper() + new[2:] + letter + ay
           print ""
           print "Your Word In PigLatin is " + new
           print ""
        replay = raw_input("Would You like To Translate Another Word? Type Yes or No and hit return.  ")
        replay = replay.lower()
        if replay in ["yes","y"]:
            main()
        else:
            print "Thank You For Using Pyglatin! The Program Will Now Terminate"
          
main()
